version: "3"
services:
  nginx:
    build: ./nginx/
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${DEV_WORKPLACE}:/var/www/html/
      - ./nginx/sites:/etc/nginx/conf.d/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/:rw
    networks:
      - net-php